#!/usr/bin/env php
<?php

array_shift($argv);

putenv('XDEBUG_MODE=coverage');

$files = [];

foreach ($argv as $file) {
	$files[] = __DIR__ . '/tests/' . $file . 'Test.php';
}

$implodedFiles = implode(' ', $files);

$command = "php vendor/bin/phpunit {$implodedFiles}";

$process = proc_open($command, [STDIN, STDOUT, STDERR], $pipes);
$result = proc_close($process);
